- HsOpenSSL.cabal
https://github.com/phonohawk/HsOpenSSL/pull/45
This will make already `cabal configure` (not `cabal build`) fail if headers cannot be found:
```
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: openssl/asn1.h
```
> Add includes cabal declaration

- OpenSSL/BN.hsc
https://github.com/phonohawk/HsOpenSSL/pull/47
Currently, both prandInteger* functions and randInteger* functions use the native function BN_rand_range. I believe that the prandInteger* functions should be using the BN_pseudo_rand_range function.
> Make prandInteger functions use BN_pseudo_rand_range

- HsOpenSSL.cabal
- OpenSSL/EVP/Internal.hsc
https://github.com/phonohawk/HsOpenSSL/pull/53
https://github.com/phonohawk/HsOpenSSL/issues/52
> Add cipherSetPadding function

- OpenSSL/Session.hsc
It's possible for SSL_CTX_new to fail. In this case the reason will be on the error stack.
(I noticed this because I just had it fail due to upgrading a library version which resulted in a segmentation fault when the context was subsequently used)
> Detect failure of SSL_CTX_new

- HsOpenSSL.cabal
- OpenSSL/BN.hsc
For now it's integer-gmp 1.0+ only (no prev versions support).
> Port BN to integer-gmp-1.0.x

- HsOpenSSL.cabal
- Setup.hs
~~~With this patch (and [cabal](https://github.com/haskell/cabal/issues/4436) being fixed) HsOpenSSL will build with ghc 8.2.~~~
Need to hack `Setup.hs` as well.
> Make it build with ghc 8.2

- HsOpenSSL.cabal
libssl32 is not available in MinGW64. It's named libssl only there.
> Support for MinGW64

- HsOpenSSL.cabal
- Setup.hs
Development versions of cabal-install or Cabal (I'm not sure which) will assume that if you don't provide a custom-setup section in your Cabal file that you don't support new versions of Cabal.
@hvr has updated the cabal-file metadata for HsOpenSSL to work with development versions of Cabal already. Putting this change into the repository will ensure that those changes survive for the next release.
Additionally I've update the Setup.hs to decide which code to use based on the Cabal version and not the GHC version. With new-build in particular GHC and Cabal versions are not related.
> Update custom setup script for Cabal-2.0

- HsOpenSSL.cabal
On my windows 10, ``-DNOCRYPT`` need to be added, otherwise build would fail with lots of message such as:
--  While building package HsOpenSSL-0.11.4.8 using:
C:\Temp\xxx\.stack-work\downloaded\II-VHbDnzs8r\.stack-work\dist\ca59d0ab\setup\setup --builddir=.stack-work\dist\ca59d0ab build lib:HsOpenSSL --ghc-options " -ddump-hi -ddump-to-file"
Process exited with code: ExitFailure 1
Logs have been written to: C:\Temp\xxx\.stack-work\logs\HsOpenSSL-0.11.4.8.log
Preprocessing library HsOpenSSL-0.11.4.8...
In file included from C:\msys64\usr\include\w32api/windows.h:95:0,
from cbits\mutex.h:5,
C:\Temp\xxx\.stack-work\downloaded\II-VHbDnzs8r\from cbits\HsOpenSSL.c:4:0: error:
C:\msys64\usr\include\w32api/wincrypt.h:1376:21: error: expected identifier or '(' before 'LPCSTR'
#define X509_NAME …
> Add ``-DNOCRYPT`` on w64-mingw

- HsOpenSSL.cabal
This gives `cabal new-build` the necessary hint that `hsc2hs` is needed,
and if missing needs to be automatically installed.
I've already revised this into the most recent release on Hackage,
-  https://hackage.haskell.org/package/HsOpenSSL-0.11.4.9/revisions/
as this was causing failures in some Travis jobs in combination with GHC 7.10.3, such as
```
Failed to build HsOpenSSL-0.11.4.9.
Build log (
/home/travis/.cabal/logs/ghc-7.10.3/HsOpenSSL-0.11.4.9-f00da0323c8dad6ca54292c9f1ed3e7d6803bb5b1c1b4d34025ec9f2fcefce2b.log
):
[1 of 1] Compiling Main             ( /home/travis/build/haskell/hackage-server/dist-newstyle/tmp/src-9421/HsOpenSSL-0.11.4.9/dist/setup/setup.hs, /home/travis/build/haskell/hackage-server/dist-newstyle/tmp/src-9421/HsOpenSSL-0.11.4.9/dist/setup/Main.o )
Linking …
```
> Declare dependency on `hsc2hs`

- cbits/HsOpenSSL.h
Your fix when using LibreSSL compiles and work on OpenBSD 6.1
Thanks
> Hack OpenSSL version number when using LibreSSL

- Setup.hs
`FlagAssignment` became an abstract type in `Cabal-2.1` (bundled with GHC 8.4.1), so we need some extra functionality to wrap and unwrap it (and some CPP for older `Cabal`s).
> Fix the build with GHC 8.4

- HsOpenSSL.cabal
For some reason, this matters when static linking.
> Link libopenssl before libcrypto.

- OpenSSL/Session.hsc
Uses `fdSocket` instead of the `MkSocket` constructor, which is no longer exposed. `fdSocket` exists at least since `network-2.0`, albeit with a non-`IO` signature until `3.0`. This is handled via CPP.
> Compatibility for network-3.0.0

- HsOpenSSL.cabal
Cabal parses
```
description:
.
Lorem ipsum dolor sit amet,
.
```
as `"\nLorem ipsum dolor sit amet,\n"` - starting and ending a description with a newline doesn't really make sense and can confuse tooling.
Would it be okay to drop them?
> .cabal: remove preceding and trailing newlines from description

- HsOpenSSL.cabal
This is the moral successor of https://github.com/vshabanov/HsOpenSSL/pull/42. Applying the suggested changes.
While OpenSSL allows some ways to discover the OpenSSL version to use leaving library discovery to pkg-config allows to a) not rely on hard coded paths and b) seamlessly use static linking once Cabal itself supports it.
> Discover OpenSSL via pkg-config

- OpenSSL/Session.hsc
- cbits/HsOpenSSL.c
- cbits/HsOpenSSL.h
Canonical disclaimer: I don't really know OpenSSL, I used https://wiki.openssl.org/index.php/Hostname_validation for reference.
Closes #14
I am not sure if the discussion in #14 concerning backwards compatibility still applies, as this PR should work with both 1.1.0 and 1.0.2 (which are not that new anymore). Maybe it is useful to expose a constant bool whether it is supported.
I tested this locally with OpenSSL 1.1.1.h with [this test code](https://gist.github.com/amesgen/13bb50b70552ac6b1ffa9ffcc9087962) by (un)commenting `enableHostnameValidation ssl host`.
> Hostname validation

- HsOpenSSL.cabal
This resolves two issues:
1. Windows configuration uses the old `eay` library which was replaced
with `libcrypto`.
2. Allow using pkg-config in Windows (e.g. in MSYS environment).
> Build fixes/improvements for Windows

- OpenSSL/Session.hsc
`contextSetDefaultVerifyPaths` configures OpenSSL to look for certificates in default locations as well as honor SSL_CERT_FILE and SSL_CERT_DIR.
> Introduce contextSetDefaultVerifyPaths

- OpenSSL/Session.hsc
The original import was broken:
```
-- original import:
foreign import ccall unsafe "SSL_CTX_set_session_id_context"
_ssl_set_session_id_context :: Ptr SSLContext_ -> Ptr CChar -> CSize -> IO CInt
```
```
-- C API:
int SSL_CTX_set_session_id_context(SSL_CTX *ctx, const unsigned char *sid_ctx,
unsigned int sid_ctx_len);
```
> Fix SSL_CTX_set_session_id_context

- HsOpenSSL.cabal
- OpenSSL/Utils.hs
- OpenSSL/X509.hsc
When `x509_verify` fails validating a certificate, it leaves a number of errors on the stack. These need to be cleared before returning, otherwise the global library state is contaminated and that can affect subsequent uses of the library.
> Clear error stack after validation failure

- HsOpenSSL.cabal
ARM Homebrew uses `/opt/homebrew` as the prefix instead of `/usr/local`.
> Support aarch64 Homebrew
